TAG 2650 - refresh groups roles
tomitribe/mykola pull request #68
Opened 2017-08-07 17:39 UTC by joaopgg

2017-08-10 13:04 UTC, Dexmaster requested changes
Requesting changes use refresh attribute please

2017-08-10 13:04 UTC, Dexmaster commented on components/angular-tomitribe-select/src/tomitribe-select.ts
> +                let refreshFn = attrs['tribeSelectFetchOnOpen'].indexOf('tribe-select-fetch-on-open') !== 0 ? attrs['tribeSelectFetchOnOpen'] : element.find('.ui-select-dropdown').attr('refresh');
This is just wrong, please fix indexOf extravaganza, 
also if possible do not use element.find you can:
 - use attribute on ui-select-choices
 - require both uiSelectCtrl and uiSelectChoicesCtrl require: ['uiSelect', 'uiSelectChoices']
 - have uiSelectCtrl.refresh and refresh function from attrs there (attrs['refresh'] without tribeSelectFetchOnOpen function)

2017-08-10 13:10 UTC, Dexmaster commented on components/angular-tomitribe-select/src/tomitribe-select.ts
> +                let refreshFn = attrs['tribeSelectFetchOnOpen'].indexOf('tribe-select-fetch-on-open') !== 0 ? attrs['tribeSelectFetchOnOpen'] : element.find('.ui-select-dropdown').attr('refresh');
Another solution you can just force trigger search change on activation which will do everything for you. Still use refresh attribute in choices for everything. Thank you.
https://github.com/angular-ui/ui-select/blob/3f097e0a717e40e6fc931b7655afcc8a3c575f91/src/uiSelectChoicesDirective.js#L63

2017-08-15 13:11 UTC, joaopgg commented
Thanks for the comments @Dexmaster, must more simple with your suggestion

2017-08-15 13:20 UTC, merged

2017-08-15 13:27 UTC, Dexmaster commented
+1

2017-08-17 12:31 UTC, pavelsmajda commented
+1